# Docker Compose version
version: '3'

# List of mounted data volumes
volumes:
  postgres_volume_local:
  redis-data:

# Список контейнеров
services:
  # Имя докер контейнера, доступное в докер-сети
  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - .env  # Указываем файл с переменными окружения
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data     

  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  migrator-local:
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local
