name: CI

on:
  push:
    branches: [ main, master, add-db ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/algol"
  IMAGE_NAME: "auth-server"
  CONTAINER_NAME: "auth-server-container"

jobs:
  # image-build-and-push:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Встаем на нужную ветку в гитхабе
  #     #- name: Checkout master
  #     - name: Checkout add-db
  #       uses: actions/checkout@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Login to Docker Registry
  #       run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

  #     - name: Build and Push Docker Image
  #       run: |
  #         TAG_NAME=$(echo $GITHUB_SHA | head -c7)
  #         docker buildx create --use
  #         docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f auth_server/Dockerfile auth_server/
  
  # Задача сборки докер образа базы
  pg-image-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout add-db
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # - name: Install Docker Compose
      #   uses: KengoTODA/actions-setup-docker-compose@v1
      #   with:
      #     version: '2.14.2'  
      
      # – name: Build Docker images
      #   run: docker-compose build

      # - name: Run Docker Compose
      #   run: |
      #     docker-compose -f ./auth_pg/docker-compose.yaml up -d --build
  
      # - name: Login to Docker Registry
      #   run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./auth_pg/docker-compose.yaml
      #     push: true
      #     tags: |
      #       pg_auth:latest

        # - name: Build Docker images
        #   run: |
        #     docker-compose -f auth_pg/docker-compose.yaml build




  # deploy-image:
  #   runs-on: ubuntu-latest
  #   needs: image-build-and-push

  #   steps:
  #     - name: Deploy to Selectel Cloud via SSH action
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSHKEY }}
  #         envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
  #         script: |
  #           # Set up variables
  #           TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            
  #           # Login into Selectel Registry
  #           docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
            
  #           # Stop running container
  #           docker stop $CONTAINER_NAME
            
  #           # Remove old container
  #           docker rm $CONTAINER_NAME
            
  #           # Run a new container from a new image
  #           docker run -d -p 50051:50051 --name $CONTAINER_NAME -t $REGISTRY/$IMAGE_NAME:$TAG_NAME